-- =====================================================================
-- Phapano+ local seed placeholder
-- =====================================================================
--
-- The previous seed created a permanent demo user with a shared password and
-- mixed legacy tables with the current migration history. It was unsafe to
-- expose through the normal Supabase seed path and has been retired.
--
-- Production and hosted environments must use the numbered migrations only.
-- A guarded, migration-aligned local sample-data process will be introduced
-- separately before public beta.
--
-- Intentionally no-op.
